[package]
name = "ads-params-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
redis = { version = "0.21.5"}
anyhow = "1.0"
serde_json = "1.0"